version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    env_file:
      - .env
      #APP_URL: 'https://www.nagacharan.site'
      #APP_SECRET: '8e4a8a5cc2c2d08c0db24829abbd2266fdd7d0589c2b2266aa44ed7190e14255'
      #DATABASE_URL: 'postgresql://postgres:H5546WneQp6b6W4d3BdI2HGA@db:5432/docmost?schema=public'
      #REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.docmost.rule=Host(nagacharan.site)'
      - 'traefik.http.services.docmost.loadbalancer.server.port=3000'
      - 'traefik.http.routers.docmost.entrypoints=websecure'
      - 'traefik.http.routers.docmost.tls.certresolver=myresolver'
      - 'traefik.docker.network=web'
    networks:
      - web

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: H5546WneQp6b6W4d3BdI2HGA
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - web

  traefik:
    restart: unless-stopped
    image: traefik:v3.0
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address:80'
      - '--entrypoints.websecure.address:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=gnagacharan24@gmail.com'
      - '--certificatesresolvers.myresolver.acme.storage=/certs/acme.json'
      - '--log.level=DEBUG'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docmost/certs:/certs
    networks:
      - web

networks:
  web:
    external: true
